var cMission = {
	name:"curiosity",
	ID: "MSL"
};

var cSpaceBrowser = {
	SOL_QUERYSTRING:"s",
	INSTR_QUERYSTRING:"i",
	PRODUCT_QUERYSTRING:"p",
	DATE_QUERYSTRING:"t",
	THUMB_QUERYSTRING: "t",
	TIMESTAMP_QUERYSTRING: "t",
	BEGIN_QUERYSTRING:"b",
	MOSAIC_QUERYSTRING: "mos",
	SHEET_QUERYSTRING: "sheet",
	OUTPUT_QUERYSTRING: "o",

	ALL_INSTRUMENTS: "All"
}